src/java/entities/Auction.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author svrundh
 */
@Entity
@XmlRootElement
@NamedQueries({
    @NamedQuery(
        name = "GetTimedOutAuctions",
        query = "SELECT a FROM Auction a WHERE (a.closingTime <= current_timestamp)"),
    @NamedQuery(
        name = "GetActiveAuctions",
        query = "SELECT a FROM Auction a WHERE (a.closingTime > current_timestamp)"),
    @NamedQuery(
        name = "GetAuctionsProducts",
        query = "SELECT a FROM Auction a WHERE a.product = :product")
})
public class Auction implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    @ManyToOne
    Product product;
    @ManyToOne
    User seller;
    @OneToOne
    Bid highestBid;
    Timestamp closingTime;
    
    @Column(precision=12, scale=2)
    BigDecimal minBid;
    
    @OneToMany(mappedBy="auction")
    private List<Bid> bids;
    
    public Auction() {
        this.bids = new ArrayList<>();
    }
    
    public Auction(Product product, BigDecimal minBid, Timestamp closingTime) {
        this.product = product;
        this.minBid = minBid;
        this.closingTime = closingTime;
        this.bids = new ArrayList<>();
    }

    public User getSeller() {
        return seller;
    }

    public void setSeller(User seller) {
        this.seller = seller;
    }

    public Timestamp getClosingTime() {
        return closingTime;
    }

    public void setClosingTime(Timestamp closingTime) {
        this.closingTime = closingTime;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public Bid getHighestBid() {
        return highestBid;
    }

    public void setHighestBid(Bid highestBid) {
        this.highestBid = highestBid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public BigDecimal getMinBid() {
        return minBid;
    }

    public void setMinBid(BigDecimal minBid) {
        this.minBid = minBid;
    }

    public List<Bid> getBids() {
        return bids;
    }

    public void setBids(List<Bid> bids) {
        this.bids = bids;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Auction)) {
            return false;
        }
        Auction other = (Auction) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "entities.Auction[ id=" + id + " ]";
    }
    
}

src/java/entities/Bid.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;

/**
 *
 * @author janinge
 */
@Entity
public class Bid implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    
    @ManyToOne
    @JoinColumn(name="auction_id")
    private Auction auction;
    
    @Column(precision=12, scale=2)
    private BigDecimal amount;
    
    @ManyToOne
    private User bidder;
    
    Timestamp created;

    public Bid(Auction auction, BigDecimal amount, User bidder) {
        this.auction = auction;
        this.amount = amount;
        this.bidder = bidder;
    }

    public Bid() {
    }
    
    @PrePersist
    protected void onCreate() {
        created = new Timestamp((new java.util.Date()).getTime());
    }

    public Timestamp getCreated() {
        return created;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Auction getAuction() {
        return auction;
    }

    public void setAuction(Auction auction) {
        this.auction = auction;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal bid) {
        this.amount = bid;
    }

    public User getBidder() {
        return bidder;
    }

    public void setBidder(User bidder) {
        this.bidder = bidder;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Bid)) {
            return false;
        }
        Bid other = (Bid) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "entities.Bid[ id=" + id + " ]";
    }
    
}

src/java/entities/Product.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entities;

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;

/**
 *
 * @author svrundh
 */
@Entity
@NamedQuery(
    name = "GetCreatorsProducts",
    query = "SELECT p FROM Product p WHERE p.creator = :user")
public class Product implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    private String name;
    private String description;
    
    @ManyToOne
    private User creator;
    
    @Lob
    private byte[] image;
    
    public Product() {
    }
    
    public Product(String name, String description, byte[] image) {
        this.name = name;
        this.description = description;
        this.image = image;
    }

    public byte[] getImage() {
        return image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public User getCreator() {
        return creator;
    }

    public void setCreator(User creator) {
        this.creator = creator;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        if (!(object instanceof Product)) {
            return false;
        }
        Product other = (Product) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Product{" + "id=" + id + '}';
    }
}

src/java/ejb/AuctionBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejb;

import entities.Auction;
import entities.Bid;
import entities.Product;
import entities.User;
import java.math.BigDecimal;
import java.security.Principal;
import java.sql.Timestamp;
import java.util.List;
import javax.annotation.Resource;
import javax.annotation.security.DeclareRoles;
import javax.annotation.security.PermitAll;
import javax.annotation.security.RolesAllowed;
import javax.ejb.SessionContext;
import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

/**
 *
 * @author janinge
 */
@Stateless
@DeclareRoles({"buyer", "seller"})
public class AuctionBean {
    @Resource SessionContext ctx;
    
    @PersistenceContext
    private EntityManager em;
    
    @PermitAll
    public List<Auction> getActiveAuctions() {
        return em.createNamedQuery("GetActiveAuctions").getResultList();
    }
    
    @RolesAllowed("buyer")
    public Auction getAuction(Long id) {
        return em.find(Auction.class, id);
    }
    
    @RolesAllowed("buyer")
    public boolean bidForAuction(BigDecimal amount, Long auctionID) {
        return bidForAuction(amount, getAuction(auctionID));
    }
    
    @RolesAllowed("buyer")
    public boolean bidForAuction(BigDecimal amount, Auction auction) {
        Bid bid = new Bid(auction, amount, resolveUser());
        
        if(bid.getAmount().compareTo(auction.getHighestBid().getAmount()) == 1
                && bid.getAmount().compareTo(auction.getMinBid()) == 1) {
            bid.setAuction(auction);
            bid.setAmount(amount);
            bid.setBidder(resolveUser());
            
            auction.setHighestBid(bid);
            
            em.persist(bid);
            em.merge(auction);
            
            return true;
        }
        
        return false;
    }
    
    @RolesAllowed("seller")
    public void createProduct(String name, String description, byte[] image) {
        Product product = new Product(name, description, image);
        product.setCreator(resolveUser());
        em.persist(product);
    }
    
    @PermitAll
    public Product getProduct(Long id) {
        return em.find(Product.class, id);
    }
    
    @RolesAllowed("seller")
    public List<Product> getOwnedProducts() {
        List<Product> products = em.createNamedQuery("GetCreatorsProducts")
                .setParameter("user", resolveUser())
                .getResultList();
        return products;
    }
    
    @PermitAll
    public List<Auction> getAuctionsForProduct(Product product) {
        List<Auction> auctions = em.createNamedQuery("GetAuctionsProducts")
                .setParameter("product", product)
                .getResultList();
        return auctions;
    }
    
    @RolesAllowed("seller")
    public void createAuction(Product product, BigDecimal minBid, Timestamp endTime) {
        Auction auction = new Auction(product, minBid, endTime);
        auction.setSeller(resolveUser());
        em.persist(auction);
    }

    private User resolveUser() {
        Principal callerPrincipal = ctx.getCallerPrincipal();
        return em.find(User.class, callerPrincipal.getName());
    }
}

web/addproduct.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/template.xhtml">
    
    <ui:define name="pagetitle">Add new product</ui:define>
    
    <ui:define name="content">
        <h:form enctype="multipart/form-data">
            <h:outputLabel for="title">Title</h:outputLabel>
            <h:inputText value="#{addProduct.title}" id="title" required="true"></h:inputText>
            
            <br/>
            
            <h:outputLabel for="description">Description</h:outputLabel>
            <h:inputTextarea value="#{addProduct.description}" id="description" required="true"></h:inputTextarea>
            
            <br/>
            
            <h:outputLabel for="image">Image</h:outputLabel>
            <h:inputFile value="#{addProduct.image}" id="image" validator="#{addProduct.validateImage}" required="true"></h:inputFile>
            
            <br/>
            
            <h:commandButton action="#{addProduct.submit}" value="Add product"></h:commandButton>
        </h:form>
    </ui:define>
</ui:composition>

web/auctions.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/template.xhtml">
    
    <ui:define name="pagetitle">Active auctions</ui:define>
    
    <ui:define name="content">
        <h:dataTable value="#{auction.activeAuctions}" var="a">
            <h:column>
                <f:facet name="header">Product</f:facet>
                
                <h:link value="#{a.product.name}" outcome="product" >
                    <f:param name="id" value="#{a.product.id}" />
                </h:link>
            </h:column>
        
            <h:column>
                <f:facet name="header">Price</f:facet>
                #{a.minBid}
            </h:column>
            
            
            <h:column>
                <f:facet name="header">End time</f:facet>
                #{a.closingTime}
            </h:column>
            
            <h:column>
                <h:link value="Bid" outcome="bid" >
                    <f:param name="id" value="#{a.id}" />
                </h:link>
            </h:column>
        </h:dataTable>
    </ui:define>
</ui:composition>

web/bid.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/template.xhtml">
    
    <f:metadata>
        <f:viewParam name="id" value="#{auction.id}" required="true"/>
        <f:viewAction action="#{auction.load}" />
    </f:metadata>
    
    <ui:define name="pagetitle">Bidding on #{auction.auction.product.name}</ui:define>
    
    <ui:define name="content">
        <p>#{auction.auction.product.description}</p>
        <p>Seller: #{auction.auction.seller.username}</p>
        
        <h3>Place bid</h3>
        <h:form>
            <h:inputText value="#{auction.newBid}" id="minbid" required="true">
                <f:validateLongRange minimum="0" />
            </h:inputText>
            <h:commandButton action="#{auction.placeBid}" value="Bid"></h:commandButton>
        </h:form>
        
        <h3>Bid history</h3>
        <h:dataTable value="#{auction.auction.bids}" var="b">
            <h:column>
                <f:facet name="header">Price</f:facet>
                #{b.amount}
            </h:column>
            
            <h:column>
                <f:facet name="header">Time</f:facet>
                #{b.created}
            </h:column>
            
            <h:column>
                <f:facet name="header">Bidder</f:facet>
                #{b.bidder.username}
            </h:column>
        </h:dataTable>
    </ui:define>
</ui:composition>

web/createprofile.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/template.xhtml">
    
    <ui:define name="pagetitle">Create profile</ui:define>
    
    <ui:define name="content">
        <h:form>
            <h:outputLabel for="username">Username</h:outputLabel>
            <h:inputText value="#{createProfile.userName}" id="username" required="true"></h:inputText>
            
            <br/>
            
            <h:outputLabel for="firstname">First name</h:outputLabel>
            <h:inputText value="#{createProfile.firstName}" id="firstname"></h:inputText>
            
            <br/>
 
            <h:outputLabel for="lastname">Last name</h:outputLabel>
            <h:inputText value="#{createProfile.lastName}" id="lastname"></h:inputText>
            
            <br/>
            
            <h:outputLabel for="email">E-mail</h:outputLabel>
            <h:inputText value="#{createProfile.email}" id="email" required="true"></h:inputText>
            
            <br/>
            
            <h:outputLabel for="password">Password</h:outputLabel>
            <h:inputSecret value="#{createProfile.password}" id="password">
                <f:validateLength minimum="8" maximum="32" />
            </h:inputSecret>
            
            <br/>

            <h:commandButton action="#{createProfile.createUser}" value="Create"></h:commandButton>
        </h:form>
    </ui:define>
</ui:composition>

web/login-error.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/template.xhtml">
    
    <ui:define name="pagetitle">Log in failed</ui:define>
    
    <ui:define name="content">
        you dun goofed
    </ui:define>

</ui:composition>

web/login-state.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    
    <h:form>
        <h:commandLink value="View profile #{user.username}" rendered="#{user.authenticated}" action="userprofile" />
        
        <br />
        
        <h:commandLink value="Log out" rendered="#{user.authenticated}" action="#{user.logout}" />
        
        <h:commandLink value="Log in" rendered="#{not user.authenticated}" action="login" />
        
        <br />
        
        <h:commandLink value="Register" rendered="#{not user.authenticated}" action="createprofile" />
        <h:link value="View auctions" outcome="auctions" />
    </h:form>
</ui:composition>

web/login.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/template.xhtml">
    
    <ui:define name="pagetitle">Log in</ui:define>
    
    <ui:define name="content">
        <h:form id="formLogin" prependId="false" onsubmit="document.getElementById('formLogin').action = 'j_security_check';">
            <h:outputLabel for="j_username" value="Username"/>
            <h:inputText id="j_username" required="true" />
            <h:outputLabel for="j_password" value="Password"/>
            <h:inputSecret id="j_password" required="true" />
              <h:commandButton value="Login" type="submit"/>
        </h:form>
    </ui:define>

</ui:composition>

web/postauction.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/template.xhtml">
    
    <ui:define name="pagetitle">Post auction</ui:define>
    
    <ui:define name="content">
            <h:form>
            <h:dataTable value="#{postAuction.products}" var="p">
                <h:column>
                    <f:facet name="header">Product</f:facet>

                    <h:link value="#{p.name}" outcome="product" >
                        <f:param name="id" value="#{p.id}" />
                    </h:link>
                </h:column>

                <h:column>
                    <f:facet name="header">Description</f:facet>
                    #{p.description}
                </h:column>

                <h:column>
                    <h:commandButton value="post" action="#{postAuction.edit(p)}" />
                </h:column>

                <h:column>
                    <h:commandButton value="delete" action="#{postAuction.delete(p)}" />
                </h:column>
            </h:dataTable>
            </h:form>

            <h:panelGroup rendered="#{postAuction.posting}">
                <h3>Publish auction for #{postAuction.editing.name}</h3>
                
                <h:form>
                <h:outputLabel for="minbid">Minimum bid</h:outputLabel>
                <h:inputText value="#{postAuction.minbid}" id="minbid" required="true">
                    <f:validateLongRange minimum="0" />
                </h:inputText>

                <br/>

                <h:outputLabel for="endtime">Expiry (in minutes)</h:outputLabel>
                <h:inputText value="#{postAuction.endtime}" id="endtime" required="true">
                    <f:validateLongRange maximum="7200" minimum="1" />
                </h:inputText>

                <br/>

                <h:commandButton action="#{postAuction.publish}" value="Publish"></h:commandButton>
                </h:form>
            </h:panelGroup>
    </ui:define>
</ui:composition>

web/product.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/template.xhtml">
    
    <f:metadata>
        <f:viewParam name="id" value="#{product.id}" required="true"/>
        <f:viewAction action="#{product.load}" />
    </f:metadata>
    
    <ui:define name="pagetitle">#{product.product.name}</ui:define>
    
    <ui:define name="content">
        <h:graphicImage value="/image/#{product.product.id}" style="height:100px;width:100px"></h:graphicImage>
        <div>#{product.product.description}</div>
        <div>Seller: #{product.product.creator.username}</div>
        
        
        <h3>Auctions</h3>
        <h:dataTable value="#{product.activeAuctions}" var="a">
            <h:column>
                <f:facet name="header">Price</f:facet>
                #{a.highestBid}
            </h:column>
            
            <h:column>
                <f:facet name="header">Closing time</f:facet>
                #{a.closingTime}
            </h:column>
            
            <h:column>
                <h:link value="Bid" outcome="bid" >
                    <f:param name="id" value="#{a.id}" />
                </h:link>
            </h:column>
        </h:dataTable>
    </ui:define>
</ui:composition>

web/template.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:h="http://xmlns.jcp.org/jsf/html">
    
        <h:head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <title>fooBay - <ui:insert name="pagetitle" /></title>
        </h:head>

        <h:body>
            <h1>fooBay</h1>
            <div id="login">
                <ui:include src="login-state.xhtml" />
            </div>
            
            <h2><ui:insert name="pagetitle" /></h2>

            <div id="content">
                <ui:insert name="content" />
            </div>
        </h:body>
</html>

web/userprofile.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/template.xhtml">
    
    <ui:define name="pagetitle">#{user.username}</ui:define>
    
    <ui:define name="content">
        <h:link value="Add product" outcome="addproduct" /><br/>
        <h:link value="Post auction" outcome="postauction" /><br/>
        
        <h3>Profile</h3>
        
        <h:panelGrid columns="2">
            <h:panelGroup>Username</h:panelGroup>
            <h:panelGroup>#{user.username}</h:panelGroup>
            
            <h:panelGroup>First name</h:panelGroup>
            <h:panelGroup>#{user.firstName}</h:panelGroup>
            
            <h:panelGroup>Last name</h:panelGroup>
            <h:panelGroup>#{user.lastName}</h:panelGroup>
            
            <h:panelGroup>Email</h:panelGroup>
            <h:panelGroup>#{user.email}</h:panelGroup>
        </h:panelGrid>
    </ui:define>
</ui:composition>